#The following are required

# Project root folder directory.(Can be changed to any other valid directory)
defaultFolderPath: .\\

# Uppercase comma-separated file extensions (according to the user's entitlements)
supportedFileExtensions: TXT,CSV
