#The following are required
defaultFolderPath: .\\ # Project root folder directory.(Can be changed to any other valid directory)
supportedFileExtensions: TXT,CSV # Uppercase comma-separated file extensions (Can be changed according to the user's entitlements)